notifications:
  slack: vqlabs:j71yKGBW4ipmLoWcJuteN83i

cache:
  directories:
    - node_modules

sudo: required

dist: trusty

language: node_js

node_js:
  - 9

addons:
  sauce_connect: true
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

matrix:
  include:
    - name: 'honestcash-editor'
      sudo: false

      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start

      install:
        - npm install

      script:
        - npm run build --prod

      after_success:
        - chmod +x ./scripts/deploy.sh
        - ./scripts/deploy.sh
